# Generated by Django 4.2.3 on 2023-08-04 04:57

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('portada', models.ImageField(upload_to='uploads/')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 8, 4, 1, 57, 30, 590908))),
                ('visibilidad', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('texto', ckeditor.fields.RichTextField(default=None)),
                ('imagen', models.ImageField(default=None, upload_to='uploads/')),
                ('link', models.TextField(default=None)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 8, 4, 1, 57, 30, 591904))),
                ('estado', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default=None)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 8, 4, 1, 57, 30, 592933))),
                ('estado', models.IntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
