# Generated by Django 4.2.3 on 2023-08-04 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 2, 0, 23, 71870)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 2, 0, 23, 73870)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 2, 0, 23, 72870)),
        ),
    ]
