# Generated by Django 4.2.3 on 2023-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
