# Generated by Django 4.2.3 on 2023-08-06 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_blog_fecha_alter_comment_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 2, 39, 11, 165812)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 2, 39, 11, 166814)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 2, 39, 11, 166814)),
        ),
    ]
