# Generated by Django 4.2.3 on 2023-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(null=None),
        ),
    ]
