# Generated by Django 4.2.3 on 2023-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_post_imagen_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(default='NULL'),
        ),
    ]
