# Generated by Django 4.2.3 on 2023-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_post_imagen_alter_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
