# Generated by Django 4.2.3 on 2023-07-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_comment_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
