# Generated by Django 4.2.3 on 2023-07-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_comment_post_id_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.BigIntegerField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.BigIntegerField(default='NULL'),
        ),
    ]
