# Generated by Django 4.2.3 on 2023-07-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_comment_post_id_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='portada',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='NULL', upload_to='uploads/'),
        ),
    ]
